### ISSUE TITLE
start job sometimes fails when waiting for nomad

### ISSUE THREAD

**Issue by gabriel-v** [liquidinvestigations/cluster#124]
at v0.13.0
```
gabriel@fritz:/opt/cluster$ docker exec -it cluster ./cluster.py supervisorctl tail -- -10000 start
nomad: ERROR (not running)
consul: ERROR (not running)
vault: ERROR (not running)
autovault: ERROR (not running)
2020-12-02 18:47:44 cluster.py        start()     INFO Deleting old Consul health checks...
consul: started
2020-12-02 18:47:52 cluster.py wait_for_consul()    DEBUG Consul has no leader
2020-12-02 18:47:54 cluster.py wait_for_consul()     INFO Consul UP and running with leader 10.42.1.1:8300
vault: started
autovault: started
2020-12-02 18:48:00 cluster.py wait_for_checks()    DEBUG Waiting 339.0s on 1 health checks for ['vault'] (self_only: True, duplicates: False)
2020-12-02 18:48:06 cluster.py wait_for_checks()     INFO Checks for ['vault'] green after 6.02s
nomad: ERROR (spawn error)
2020-12-02 18:48:11 cluster.py        start()  WARNING initial Nomad start failed: Command '['supervisorctl', '-c', '/opt/cluster/etc/supervisord.conf', 'start', 'nomad']' returned non-zero exit status 7.
2020-12-02 18:48:11 cluster.py restart_nomad_until_it_works()  WARNING Waiting for Nomad... <urlopen error [Errno 111] Connection refused>
2020-12-02 18:48:14 cluster.py restart_nomad_until_it_works()  WARNING Waiting for Nomad... <urlopen error [Errno 111] Connection refused>
2020-12-02 18:48:17 cluster.py     <module>()    ERROR Remote end closed connection without response
Traceback (most recent call last):
  File "/opt/cluster/cluster.py", line 866, in <module>
    cli()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/cluster/cluster.py", line 805, in start
    restart_nomad_until_it_works()
  File "/opt/cluster/cluster.py", line 761, in restart_nomad_until_it_works
    leader = nomad.get('/status/leader')
  File "/opt/cluster/cluster.py", line 216, in get
    return self.send(req)
  File "/opt/cluster/cluster.py", line 208, in send
    with urlopen(req) as res:
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1378, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1353, in do_open
    r = h.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 279, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without 
```

**Comment by gabriel-v** [comment]
haven't seen this
