### ISSUE TITLE
influxdb: check "http" is missing

### ISSUE THREAD

**Issue by salevajo** [liquidinvestigations/cluster#125]
```
2021-01-25 12:15:09 cluster.py     <module>()    ERROR Checks are failing after 333.31s:
 -
 - influxdb: check "http" is missing
Traceback (most recent call last):
  File "./cluster.py", line 866, in <module>
    cli()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "./cluster.py", line 747, in wait
    k: v for k, v in HEALTH_CHECKS.items()
  File "./cluster.py", line 677, in wait_for_checks
    raise RuntimeError(msg)
RuntimeError: Checks are failing after 333.31s:
 -
 - influxdb: check "http" is missing
```

**Comment by salevajo** [comment]
After a while, within Nomad it looks like this...

<img width="1441" alt="Screenshot 2021-01-25 at 15 53 58" src="https://user-images.githubusercontent.com/572515/105724067-c184c800-5f27-11eb-96ec-570e156120fd.png">

**Comment by gabriel-v** [comment]
Known issue; required RAM for influxdb grows with time:
https://community.influxdata.com/t/addressing-the-growing-ram-vs-usage-issue-aka-unexpected-out-of-memory/6339

When this happens, you can either:
- remove the data (`rm -rf cluster/var/volumes/influxdb`), or
- give it 6-8GB RAM (it seems to top out at around this usage)

**Comment by gabriel-v** [comment]
influxdb deleted
